[2025-05-07T12:54:51.362+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=extract_data permission to 509
[2025-05-07T12:54:51.363+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=extract_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=extract_data'
[2025-05-07T12:54:51.537+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=extract_data permission to 509
[2025-05-07T12:54:51.538+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=extract_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=extract_data'
[2025-05-07T12:54:51.622+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: anime_etl_pipeline.extract_data manual__2025-05-07T12:54:45.110872+00:00 [queued]>
[2025-05-07T12:54:51.666+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: anime_etl_pipeline.extract_data manual__2025-05-07T12:54:45.110872+00:00 [queued]>
[2025-05-07T12:54:51.669+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2025-05-07T12:54:51.807+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): extract_data> on 2025-05-07 12:54:45.110872+00:00
[2025-05-07T12:54:51.815+0000] {standard_task_runner.py:57} INFO - Started process 290 to run task
[2025-05-07T12:54:51.823+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'anime_etl_pipeline', 'extract_data', 'manual__2025-05-07T12:54:45.110872+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp4f2eb03l']
[2025-05-07T12:54:51.824+0000] {standard_task_runner.py:85} INFO - Job 204: Subtask extract_data
[2025-05-07T12:54:52.014+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=extract_data permission to 509
[2025-05-07T12:54:52.016+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=extract_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=extract_data'
[2025-05-07T12:54:52.019+0000] {task_command.py:415} INFO - Running <TaskInstance: anime_etl_pipeline.extract_data manual__2025-05-07T12:54:45.110872+00:00 [running]> on host b21373046c31
[2025-05-07T12:54:53.422+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='anime_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T12:54:45.110872+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T12:54:45.110872+00:00'
[2025-05-07T12:54:54.407+0000] {logging_mixin.py:151} INFO - Extract task is running...
[2025-05-07T12:54:54.413+0000] {logging_mixin.py:151} INFO - Database connection succeeded ----Extract.py
[2025-05-07T12:54:54.503+0000] {logging_mixin.py:151} INFO - After Extraction, the entries have been deleted.
[2025-05-07T12:54:54.504+0000] {logging_mixin.py:151} INFO - Data extracted from the Database and saved successfully at Data_Versioning/ETL_Data/extracted_data.csv
[2025-05-07T12:54:55.397+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-07T12:54:55.423+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=anime_etl_pipeline, task_id=extract_data, execution_date=20250507T125445, start_date=20250507T125451, end_date=20250507T125455
[2025-05-07T12:54:55.577+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-07T12:54:55.670+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
